/*
  pgfindlib.h - the file that's #included in pgfindlib.c and anything that calls it.

  Copyright (c) 2025 by Peter Gulutzan. All rights reserved.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; version 2 of the License.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

  For explanation see the README.md file which comes with the readmyso package
*/

#ifndef PGFINDLIB_H
#define PGFINDLIB_H
extern int pgfindlib(const char *statement, char *buffer, unsigned int buffer_max_length);

#define PGFINDLIB_OK 0
#define PGFINDLIB_ERROR_BUFFER_MAX_LENGTH_TOO_SMALL -1
#define PGFINDLIB_ERROR_NULL -2
#define PGFINDLIB_ERROR_MAX_PATH_LENGTH_TOO_SMALL -3
#define PGFINDLIB_MALLOC_BUFFER_1_OVERFLOW -4
#define PGFINDLIB_MALLOC_BUFFER_2_OVERFLOW -5
#define PGFINDLIB_STATEMENT_SYNTAX -6

/* PGFINDLIB_INCLUDE_ items must be 0 or 1. To not include, say e.g. -DPGFINDLIB_INCLUDE_COMMENT_AT_START=0 */

#ifndef PGFINDLIB_INCLUDE_LD_AUDIT
#define PGFINDLIB_INCLUDE_LD_AUDIT 1
#endif

#ifndef PGFINDLIB_INCLUDE_LD_PRELOAD
#define PGFINDLIB_INCLUDE_LD_PRELOAD 1
#endif

#ifndef PGFINDLIB_INCLUDE_DT_RPATH_OR_DT_RUNPATH
#define PGFINDLIB_INCLUDE_DT_RPATH_OR_DT_RUNPATH 1
#endif

#ifndef PGFINDLIB_INCLUDE_LD_LIBRARY_PATH
#define PGFINDLIB_INCLUDE_LD_LIBRARY_PATH 1
#endif

#ifndef PGFINDLIB_INCLUDE_LD_RUN_PATH
#define PGFINDLIB_INCLUDE_LD_RUN_PATH 1
#endif

#ifndef PGFINDLIB_INCLUDE_LD_SO_CACHE
#define PGFINDLIB_INCLUDE_LD_SO_CACHE 1
#endif

#ifndef PGFINDLIB_INCLUDE_DEFAULT_PATHS
#define PGFINDLIB_INCLUDE_DEFAULT_PATHS 1
#endif

#ifndef PGFINDLIB_INCLUDE_EXTRA_PATHS
#define PGFINDLIB_INCLUDE_EXTRA_PATHS 1
#endif

#ifndef PGFINDLIB_INCLUDE_GET_LIB_OR_PLATFORM
#define PGFINDLIB_INCLUDE_GET_LIB_OR_PLATFORM 1
#endif

#ifndef PGFINDLIB_INCLUDE_SYMLINKS
#define PGFINDLIB_INCLUDE_SYMLINKS 1
#endif

#ifndef PGFINDLIB_INCLUDE_HARDLINKS
#define PGFINDLIB_INCLUDE_HARDLINKS 1
#endif

#ifndef PGFINDLIB_INCLUDE_COMMENT_AT_START
#define PGFINDLIB_INCLUDE_COMMENT_AT_START 1
#endif
#ifndef PGFINDLIB_INCLUDE_COMMENT_SOURCE_NAME
#define PGFINDLIB_INCLUDE_COMMENT_SOURCE_NAME 1
#endif
#ifndef PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED
#define PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED 1
#endif
#ifndef PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM
#define PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM 1
#endif

/* Every column in a buffer output row ends with ", " but you can redefine e.g. to ":" if worried that filenames contain commas */
#define PGFINDLIB_COLUMN_DELIMITER ", "
#define PGFINDLIB_ROW_DELIMITER "\n"
#define MAX_COLUMNS_PER_ROW 7
#define COLUMN_FOR_ROW_NUMBER 0
#define COLUMN_FOR_PATH 1
#define COLUMN_FOR_SOURCE 2
#define COLUMN_FOR_COMMENT_1 3
#define COLUMN_FOR_COMMENT_2 4
#define COLUMN_FOR_COMMENT_3 5

/* Values that can be compared to flags */
#define PGFINDLIB_ROW_VERSION                    (0x001 * PGFINDLIB_INCLUDE_COMMENT_AT_START)
#define PGFINDLIB_COMMENT_LIB                        (0x002 * PGFINDLIB_INCLUDE_COMMENT_AT_START)
#define PGFINDLIB_COMMENT_ACCESS_LDCONFIG_FAILED     (0x200 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_CANNOT_READ_RPATH          (0x201 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_CANNOT_READ_RUNPATH        (0x202 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_LDCONFIG_FAILED            (0x203 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_ELF_AUX_INFO_FAILED        (0x204 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_READLINK_FAILED            (0x205 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_NO_TRUE_OR_CP              (0x206 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_EHDR_IDENT                 (0x207 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_CANT_FIND_DYNAMIC_LOADER   (0x208 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_CANT_ACCESS_DYNAMIC_LOADER (0x209 * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_ASSUMING_LIB               (0x20a * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_UNAME_FAILED               (0x20b * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_ASSUMING_PLATFORM          (0x20c * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_MAX_INODE_COUNT_TOO_SMALL  (0x20d * PGFINDLIB_INCLUDE_COMMENT_UNEXPECTED)
#define PGFINDLIB_COMMENT_REPLACE_STRING             (0x300 * PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM)
#define PGFINDLIB_COMMENT_ACCESS_NEXT_FAILED         (0x301 * PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM)
#define PGFINDLIB_COMMENT_SYMLINK                    (0x302 * PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM)
#define PGFINDLIB_COMMENT_NEXT_DUPLICATE             (0x303 * PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM)
#define PGFINDLIB_COMMENT_STAT_NEXT_FAILED           (0x304 * PGFINDLIB_INCLUDE_COMMENT_RE_NEXT_ITEM)
#define PGFINDLIB_IF_GET_LIB_OR_PLATFORM             (0x408 * PGFINDLIB_INCLUDE_GET_LIB_OR_PLATFORM)
#define PGFINDLIB_IF_SYMLINKS                        (0x409 * PGFINDLIB_INCLUDE_SYMLINKS)
#define PGFINDLIB_IF_HARDLINKS                       (0x4a0 * PGFINDLIB_INCLUDE_HARDLINKS)
#define PGFINDLIB_COMMENT_STATEMENT_SYNTAX           5000

/* These are out of order ... */
#define PGFINDLIB_COMMENT_LIB_STRING         5
#define PGFINDLIB_COMMENT_PLATFORM_STRING    56
#define PGFINDLIB_COMMENT_ORIGIN_STRING      567

#define PGFINDLIB_TOKEN_SOURCE_DT_RPATH_OR_DT_RUNPATH       (0x12 * PGFINDLIB_INCLUDE_DT_RPATH_OR_DT_RUNPATH)

/* Token numbrs. the ..._SOURCE_... ones correspond to what's in pgfindlib_standard_source_array in pgfindlib.c, plus 1 */
#define PGFINDLIB_TOKEN_SOURCE_LD_AUDIT                     (1 * PGFINDLIB_INCLUDE_LD_AUDIT)
#define PGFINDLIB_TOKEN_SOURCE_LD_PRELOAD                   (2 * PGFINDLIB_INCLUDE_LD_PRELOAD)
#define PGFINDLIB_TOKEN_SOURCE_DT_RPATH                     (3 * PGFINDLIB_INCLUDE_DT_RPATH_OR_DT_RUNPATH)
#define PGFINDLIB_TOKEN_SOURCE_LD_LIBRARY_PATH              (4 * PGFINDLIB_INCLUDE_LD_LIBRARY_PATH)
#define PGFINDLIB_TOKEN_SOURCE_DT_RUNPATH                   (5 * PGFINDLIB_INCLUDE_DT_RPATH_OR_DT_RUNPATH)
#define PGFINDLIB_TOKEN_SOURCE_LD_RUN_PATH                  (6 * PGFINDLIB_INCLUDE_LD_RUN_PATH)
#define PGFINDLIB_TOKEN_SOURCE_LD_SO_CACHE                  (7 * PGFINDLIB_INCLUDE_LD_SO_CACHE)
#define PGFINDLIB_TOKEN_SOURCE_DEFAULT_PATHS                (8 * PGFINDLIB_INCLUDE_DEFAULT_PATHS)
#define PGFINDLIB_TOKEN_SOURCE_EXTRA_PATHS                  (9 * PGFINDLIB_INCLUDE_EXTRA_PATHS)
#define PGFINDLIB_TOKEN_SOURCE_NONSTANDARD                  10
#define PGFINDLIB_TOKEN_FROM                                11
#define PGFINDLIB_TOKEN_WHERE                               12
#define PGFINDLIB_TOKEN_FILE                                13
#define PGFINDLIB_TOKEN_COMMA                               14
#define PGFINDLIB_TOKEN_END                                 15
#define PGFINDLIB_TOKEN_UNKNOWN                             17

#ifndef PGFINDLIB_MAX_INODE_COUNT
#define PGFINDLIB_MAX_INODE_COUNT 100
#endif

#ifndef PGFINDLIB_MAX_PATH_LENGTH
#define PGFINDLIB_MAX_PATH_LENGTH 4096
#endif

#ifndef PGFINDLIB_MAX_TOKENS_COUNT
#define PGFINDLIB_MAX_TOKENS_COUNT 20
#endif

#define PGFINDLIB_MAX_TOKEN_LENGTH PGFINDLIB_MAX_PATH_LENGTH

#ifndef PGFINDLIB_FREEBSD
#if defined(__FreeBSD__)
#define PGFINDLIB_FREEBSD
#endif
#endif

#define PGFINDLIB_VERSION_MAJOR 0
#define PGFINDLIB_VERSION_MINOR 9
#define PGFINDLIB_VERSION_PATCH 6

#endif
